### ISSUE TITLE
Glide + CDN services

### ISSUE THREAD

**Issue by darkponyhq** [thephpleague/glide#233] opened 2018-05-28 17:11 UTC
Hi there,

Glide is an amazing library. The only major drawback we came across during the last two years we are using it, is the "by design" problem with dynamic cropping. 

Cropping (and other functionality) is being pass as a query string on the url, e.g.

yourdomain.com/image.jpg?w=300&h=300&fit=crop

The problem with all the CDN services I came across is that the standard pull/fetch service ignores the query string, so if the images are served via CDN all the custom cropping is gone!

It was discussed in this post

https://github.com/thephpleague/glide/issues/170

the posibility of pushing this query data within the URL, is this implemented? 

e.g.

http://example.com/img/kayaks.jpg/w-800-h-500-fit-crop-s-5ac7f6163057bf1931fd5b513f797644939ece7724ee3846a27e9915f3ea5eda.jpg

This will solve the problem since CDN services will fetch the right data and there will be no query info to discard. It is not as SEO friendly as it could, be the CDN issue is major (at least for us).

Thanks again for this amazing library.

**Comment by calumbrodie** [comment] 2018-06-18 17:16
Every CDN I've ever used allows you to cache based on query strings so I'm not 100% what the issue is here?

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/QueryStringParameters.html

Cloudflare has this feature within page rules.

Is it that it's just less hassle/setup to use a filename/path than using query strings?

**Comment by tgalopin** [comment] 2021-01-24 20:34
Planned for the next major, closing as duplicate of https://github.com/thephpleague/glide/issues/288

**Closed by tgalopin** 2021-01-24 20:34 UTC
