### ISSUE TITLE
Adds unwanted borders to images when using the orientation parameter

### ISSUE THREAD

**Issue by nathan-mickler** [thephpleague/glide#103] opened 2015-10-09 15:08 UTC
When I use the &or=0 parameter, it adds a border.
When I do NOT use that parameter, it does NOT add a border.
It also does NOT add a border when using or=90, or=180, and or=270

(see images below)
![screen shot 2015-10-09 at 10 07 13 am](https://cloud.githubusercontent.com/assets/14879121/10397512/b4ffdab2-6e6d-11e5-9bbc-d64122911f27.png)
![screen shot 2015-10-09 at 10 07 19 am](https://cloud.githubusercontent.com/assets/14879121/10397510/b4fb745e-6e6d-11e5-808f-dba10f33b5c4.png)

**Comment by reinink** [comment] 2015-10-09 15:23
Interesting. What version of Glide are you using?

**Comment by nathan-mickler** [comment] 2015-10-09 15:50
Just updated to the 1.0 version to see if it would fix the problem...but seems to exist on both 0.3 and 1.0 versions.

**Comment by reinink** [comment] 2015-10-09 16:10
Are you using GD, or Imagick?

**Comment by nathan-mickler** [comment] 2015-10-09 19:07
I'm not explicitly defining the image handling library - doesn't it default to GD?

**Comment by reinink** [comment] 2015-10-09 20:13
Yes, it defaults to GD. So, I'm not really sure exactly what's happening here. Version 0.3 of Glide didn't even have border support, so it's impossible that it happened because of that. It almost looks like your image may be a transparent PNG, with a 1px or 2px transparent border around the outside. Then, when the image is being created as JPEG, a black background is automatically applied, causing a border look like this. Can you confirm if that is the case?

**Comment by nathan-mickler** [comment] 2015-10-09 20:18
I will check the picture and let you know on Monday, but if that was the
case, wouldn't the picture have a border when rotated 90 degrees or more?
When I use or=auto or or=90 it doesn't have a border.

Only happens with or=0

**Comment by nathan-mickler** [comment] 2015-10-12 13:59
These were JPG files, so there isn't any transparent border around the outside - any other ideas what it could be?

**Comment by reinink** [comment] 2015-10-13 10:43
Would you mind emailing me (jonathan@reinink.ca) the source image so I can run some tests?

**Comment by reinink** [comment] 2015-12-20 12:24
I'm going to close this, as I haven't received an test image. However, if you still need help, please feel free to email me and I'll doing some testing on my end. Thanks!

**Closed by reinink** 2015-12-20 12:24 UTC

**Comment by univers-andrew** [comment] 2023-04-25 03:25
Hi @reinink, I'm observing this same issue using [Spatie's 'Responsive Images' addon ](https://github.com/spatie/statamic-responsive-images) for Statamic, which is using Glide [under the hood](https://statamic.dev/tags/glide#basic-usage). 

It seems like this has been an ongoing issue for sometime, but hasn't reared it's head enough to be esacalated, Saw a few different comments/threads on Statamic's different support channels like this one: https://statamic.com/forum/5378-glide-images-black-top-border. I remember having the issue myself on a previous project, but managed to find a workaround at the time.

I have confirmed the original image file(s) don't contain any border, and there aren't any transparency issues at play as the source files are jpgs. I can also confirm there is no CSS at play creating the border — it's within the generated image output. 

I'm not doing anything particularly unusual. Here's the snippet I'm using with Spaties responsive images tag:

`{{ responsive:image alt="{alt}" ratio=".75" glide:width="900" }}`

Strangely enough, when I remove the `glide:width="900"` attribute (which sets a max width of variations to be generated) the border dissapears.... when I add it back the border returns! It doesn't happen on all images, so it seems like it could be a bug/issue depending on the cropping required for that specific image, but that's just speculation on my part!

This is happening with the default GD driver, haven't tried using Imagick for this site yet, but will test this down the track possibly.

Some screenshots for reference below:
<img width="1639" alt="Screenshot 2023-04-25 at 11 59 30 am" src="https://user-images.githubusercontent.com/122848318/234156604-6ec592cb-529f-4e45-8d5c-782ce0682e89.png">

<img width="1485" alt="Screenshot 2023-04-25 at 11 32 37 am" src="https://user-images.githubusercontent.com/122848318/234156587-3cc1fe76-49f6-4e85-8630-95bde2abd8c4.png">


Happy to supply further info as required. Would love to assit in squashing this bug — it's the only issue I've had with Glide to date! if you think I should raise this directly with Statamic as well do let me know

With thanks,
Andrew
