### ISSUE TITLE
[Question] Remove cache for a particular original

### ISSUE THREAD

**Issue by JulienTant** [thephpleague/glide#53] opened 2015-03-26 10:06 UTC
Hello,

I just wanted to know if there's a way to remove the cache for a particular original picture ?

**Comment by schmidex** [comment] 2015-03-27 10:03
Looking at the source there isn't a feature like this. The problem is, cache files don't have any reference to their original file they were created from. This is because the cache-filenames are simple hashes of the filename+parameters.
Maybe this could be changed to something like this:
```php
// remove folders from filename
$preparedfilename = str_replace('/','-',$filename);
// generate cachefilename
$cachefilename = $preparedfilename . '_' . md5($parameters);
```

Now a method could do something like this:
```php
public function deleteCache($filename)
{
    $search = $str_replace('/','-',$filename);
    
    $path = $this->flysystem->listContents('cache-path');
    foreach($path as $file)
    {
        if( some regex) ->delete file
    }
}
```

**Comment by JulienTant** [comment] 2015-03-27 10:17
Because i'm using a class to generate my configuration arrays instead of using the Request directly, i did a loop over all options and checked if cache exists. If yes, i removed the cache file.

I guess another solution would be to maintain a json file maybe ?

**Comment by constb** [comment] 2015-03-31 12:27
maybe a task at hand could be solved by this pull request: https://github.com/thephpleague/glide/pull/28? I really have no idea why it hasn't been merged yet.

**Comment by reinink** [comment] 2015-06-15 14:55
Please see issue #7 for more information on this. To keep things organized, we'll continue this discussion there, and I'm going close this issue.

@constb the reason that PR wasn't merged in was because:

1. It required extra Flysystem API calls, which can slow things down, especially using an Amazon S3 adapter, or some other non-local adapter.
2. It doesn't really help at all when the browser has cached the file anyway, since it will never actually hit Glide to check if the freshness has changed.

**Closed by reinink** 2015-06-15 14:55 UTC
