### ISSUE TITLE
Images load time very slow any suggestions?

### ISSUE THREAD

**Issue by janekbar5** [thephpleague/glide#339] opened 2022-01-04 10:20 UTC
Really like the glide and flexibility it gives. However the images loading time is very slow. Is there a way to improve it. The issue exist both on local pc and server. Not sure where to start is it the Apache problem or the glide library?
![glide](https://user-images.githubusercontent.com/12866020/148044487-4a019f28-aae1-4c3f-9c31-9ffd01aeb1f4.jpg)

**Comment by Awilum** [comment] 2022-01-04 12:08
Hello @janekbar5
After a few years of Glide usage, I stop using it
1 - https://github.com/thephpleague/glide/issues/330
2 - https://github.com/flextype/flextype/issues/574

**Comment by janekbar5** [comment] 2022-01-04 15:23
thanks @Awilum also thinking going back to intervention perhaps

**Comment by ADmad** [comment] 2022-01-04 16:39
Duplicate of #287

**Closed by ADmad** 2022-01-04 16:39 UTC
