### ISSUE TITLE
All sample images on the site are broken.

### ISSUE THREAD

**Issue by Awilum** [thephpleague/glide#331] opened 2021-09-03 07:26 UTC
If we will open any page here by clicking on **Info** link, page will be opened with broken images.
https://glide.thephpleague.com/2.0/api/quick-reference/

**Actual result:** Images are broken
**Expected result:** Images should be displayed

**Comment by ADmad** [comment] 2021-09-03 07:53
Duplicate of #328

**Closed by ADmad** 2021-09-03 07:53 UTC
