### ISSUE TITLE
Cached images/files are empty when using Dropbox as source

### ISSUE THREAD

**Issue by jasonvarga** [thephpleague/glide#31] opened 2015-01-30 19:51 UTC
I'm running into an issue where using Dropbox as the source is creating empty cache files.

I've tried Local, Dropbox and S3 in all combinations of source/cache. They all work except when using Dropbox as the source. I'm even able to cache _to_ Dropbox just fine.

When Dropbox is the source, the cache files get generated in the correct place, but they contain no data.

Do you have any ideas? Please let me know what other information I can give you that'd be helpful.

Thanks!

**Comment by reinink** [comment] 2015-01-30 19:53
Hey, thanks for giving Glide a try! To be honest I haven't actually given Glide a try with the Dropbox adapter yet, so I can't say I've run into this. I'll have to do some testing to see if the issue is with Glide, or Flysystem. Maybe @frankdejonge can comment—he might know what's wrong right away.

**Comment by jasonvarga** [comment] 2015-01-30 20:02
Thanks for the fast response. Glide seems really great so far. Again, let me know if there's anything I can give you to help track this down. I'm a little stumped.

**Comment by jasonvarga** [comment] 2015-01-30 20:27
Okay so I originally set up my server using the example in "[Setup manually](http://glide.thephpleague.com/config/the-server/)" where I defined everything separately.

Changing it to use a `ServerFactory` works.

I can't tell what the difference between the two methods appears to be exactly, but everything seems fine now!

**Comment by reinink** [comment] 2015-01-30 20:30
Hmm, well that's good I guess, haha, but it doesn't make sense. Both approaches should work. Do you mind sharing with me your original code that did not work? I'd love to see if I can see what went wrong, because you should be able to manually instantiate all the objects if you so desire.

**Comment by jasonvarga** [comment] 2015-01-30 20:39
Sure. Before:

``` php
use League\Glide\Server;
use League\Glide\Api\Api;
use League\Glide\Api\Manipulator;
use Intervention\Image\ImageManager;

private function createServer()
{
  $source = $this->flysystem->connection('dropbox');
  $cache  = $this->flysystem->connection('awss3');

  $imageManager = new ImageManager(['driver' => 'gd']);

  $manipulators = [
    new Manipulator\Orientation(),
    new Manipulator\Rectangle(),
    new Manipulator\Size(null),
    new Manipulator\Brightness(),
    new Manipulator\Contrast(),
    new Manipulator\Gamma(),
    new Manipulator\Sharpen(),
    new Manipulator\Filter(),
    new Manipulator\Blur(),
    new Manipulator\Pixelate(),
    new Manipulator\Output()
  ];

  $api = new Api($imageManager, $manipulators);

  $server = new Server($source, $cache, $api);

  $server->setCachePathPrefix($this->account);
  $server->setBaseUrl('/img/');

  return $server;
}
```

After:

``` php
use League\Glide\ServerFactory;

private function createServer()
{
  return ServerFactory::create([
    'source' => $this->flysystem->connection('dropbox'),
    'cache'  => $this->flysystem->connection('awss3'),
    'cache_path_prefix' => $this->account,
    'base_url' => 'img'
  ]);
}
```

**Comment by jasonvarga** [comment] 2015-01-30 20:50
Oh, and I'm using `$this->flysystem->connection($adapter)` because I'm using [Laravel-Flysystem](https://github.com/GrahamCampbell/Laravel-Flysystem). They each return a `Filesystem`.

**Comment by reinink** [comment] 2015-01-30 20:53
Yeah, that's cool, and I'm familiar with that library.

As for your code above, it looks perfect to me, meaning I'm actually going to have to fire up and editor and try it myself to see where it's going wrong. I'll get back to you on this tomorrow probably, I'm running out of time today.

**Comment by jasonvarga** [comment] 2015-01-30 20:56
No rush though, like I said, it's working now. Using a factory is better for me anyway.

**Comment by reinink** [comment] 2015-02-02 14:28
Okay I've tested your code myself and I cannot reproduce the bug. Since you seem to be getting on fine with the factory I'm just going to close this issue.

**Closed by reinink** 2015-02-02 14:28 UTC
